service: screenshottr-service


provider:
  name: aws
  runtime: nodejs6.10

stage: dev
region: us-east-1


plugins:
  - serverless-offline
iamRoleStatements:
  - Effect: "Allow"
   Action:
     - "s3:*"
   Resource: "arn:aws:s3:::screenshottr-service-images-unprocessed-dev*"
  - Effect: "Allow"
   Action:
     - "s3:*"
   Resource: "arn:aws:s3:::screenshottr-service-images-saved-dev/*"
  - Effect: "Allow"
    Action:
      - "dynamodb:*"
  Resource: "arn:aws:dynamodb:us-east-1:660773155982:table/screenshottr-service-uploads"

functions:
  getSignedS3URL:
    handler: src/getSignedS3URL.getSignedS3URL
    events:
      - http: GET api/getSignedS3URL
  processUpload:
    handler: src/processUpload.processUpload
    events:
      - s3: screenshottr-service-images-unprocessed-dev

resources:
 Resources:
   storageBucket:
     Type: AWS::S3::Bucket
     Properties:
       BucketName: screenshottr-service-images-saved
    entriesDynamo:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: screenshottr-service-uploads
        AttributeDefinitions:
          - AttributeName: image_id
            AttributeType: S
        KeySchema:
          - AttributeName: image_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
 # Outputs:
 #    NewOutput:
 #      Description: "Description for the output"
 #      Value: "Some output value"
