service: screenshottr-service


provider:
  name: aws
  runtime: nodejs6.10

stage: dev
region: us-east-1


plugins:
  - serverless-offline
# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"


functions:
  getSignedS3URL:
    handler: src/getSignedS3URL.getSignedS3URL
    events:
      - http: GET api/getSignedS3URL
  uploadFile:
    handler: src/uploadFile.uploadFile
    events:
      - http: POST api/uploadFile
  processUpload:
    handler: src/processUpload.processUpload
    events:
      - s3: screenshottr-service-images-unprocessed-dev

resources:
 Resources:
   # uploadsBucket:
   #   Type: AWS::S3::Bucket
   #   Properties:
   #     BucketName: screenshottr-service-images-unprocessed-dev
   storageBucket:
     Type: AWS::S3::Bucket
     Properties:
       BucketName: screenshottr-service-images-saved-dev
 # Outputs:
 #    NewOutput:
 #      Description: "Description for the output"
 #      Value: "Some output value"
