version: 2
jobs:
  build:
    docker:
      - image: node
    steps:
      - checkout
      - run:
          name: Yarn Install
          command: yarn install
      - run:
          name: Serverless Deploy
          command: serverless deploy
